### ISSUE TITLE
RCWL-0516 Bouncing

### ISSUE THREAD

**Issue by jkknighton** [jdesbonnet/RCWL-0516#59]
Newbie here.  I'm using an RCWL-0516 with a D1 Mini through Home Assistant to trigger a light on when someone enters a room.  The issue I am having it just keeps bouncing from Detected to Clear every few seconds.  This is the 2nd one I've tried with the same issue, the first one was with an ESP32.  I know I must be doing something wrong or maybe there's something I need to add?  Here is the ESPHome code that I uploaded to the D1 Mini.  Thank you.

```
esphome:
  name: mw_sensor01
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "XXXX"
  password: "XXXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mw Sensor01 Fallback Hotspot"
    password: "kta0sKXAWsgS"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: D4
    name: "Kitchen Sensor"
    device_class: motion
    #filters:
      #- delayed_on_off: 4000ms
```
